steps:
  # Step 1: Clean the current directory.
  - name: 'bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'rm -rf ./*'

  # Step 2: Checkout your source code from your repository.
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Arssssl/imtisalCICD', 'imtisalCICD']
    
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - '--version'

  # Step 3: Install necessary Cloud SDK components.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'components'
      - 'install'
      - 'beta'
      - 'functions'
      - '-q'  # Quiet mode to skip prompts

  # Step 4: Deploy your Cloud Function (Python).
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'functions'
      - 'deploy'
      - 'helloWorldFunction'
      - '--runtime'
      - 'python311'
      - '--trigger-http'
      - '--entry-point'
      - 'hello_world'
      - '--source'
      - '.'
      - '--version'
      - '444.0.0'
