steps:
  # Step 1: Clean the current directory.
  - name: 'bash'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'rm -rf ./*'

 

  # Step 2: Checkout your source code from your repository.
   - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Arssssl/imtisalCICD.git', 'imtisalCICD']


  # Step 2: Install dependencies (if any).
  # - name: 'gcr.io/cloud-builders/pip'
  #   args: ['install', '-r', 'requirements.txt']

  # Step 3: Deploy your Cloud Function (Python).
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: [
      'functions', 'deploy', 'helloWorldFunction',
      '--runtime', 'python38',  # Specify the Python runtime version.
      '--trigger-http', '--entry-point', 'hello-world-function',  # Replace 'your_python_function' with your Python function name.
      '--source', '.'
    ]
